### PR TITLE
feat: add configure_mode & configure_devtool attributes to webpack_bundle and webpack_devserver

### PR DESCRIPTION
**Pull request by gregmagolan**
In some cases, users don't want the generated base config to touch mode & devtool

### CODE REVIEW

**Comment by jbedard** [comment]
These can't be overridden in the user config files? We need to explicitly not set them? 🫤

**Comment by gregmagolan** [comment]
> These can't be overridden in the user config files? We need to explicitly not set them? 🫤

They can be but users might not pass config files or just want the default behaviour

**Comment by jbedard** [comment]
How common is it to not have a config and not want default behavior? If it's rare I'd vote to not add more to the API. Or maybe add a single flag "use_defaults" or something like that? Then that flag can just swap between preset config files...

**Comment by gregmagolan** [comment]
So far one request from a client but it is a low sample size so I don't think we can know how common it will be.
I considered `use_defaults` but the generated base config does have sane and useful defaults for `infrastructureLogging`, `optimization` & `output` that I don't think makes sense to be able to turn off. Just `mode` and `devtool` are the contentious ones for the client.

**Review by kormide — APPROVED** [review]

**Pull request merged**
