### PR TITLE
fix: remove extension constraint on webpack_config

### LINKED ISSUE #33: Typescript defined config file
I've been using webpack with a typescript config file. Unfortunately, the webpack_bundle rule is not allowing this:

```
(14:32:23) ERROR: BUILD.bazel:130:15: in webpack_config attribute of webpack_bundle rule //:bundle_dev: source file '//:webpack-dev-build.config.ts' is misplaced here (expected .js)
```

Webpack supports typescript itself:
https://webpack.js.org/configuration/configuration-languages/#typescript

Just looks like an incorrect restriction from the Bazel rule

### PR DESCRIPTION
**Pull request by thesayyn**
Closes #33

### CODE REVIEW

**Comment by jbedard** [comment]
What is supported other then js/ts? Should we limit it still?

Worth adding a test if there's a super simple one to copy+paste+switch-to-ts?

**Comment by thesayyn** [comment]
> What is supported other then js/ts? Should we limit it still?

Officially probably just js and ts. I just don't want to list every single of them. Probably you could use loaders to use other extensions as well. I don't see a reason why we should list them.

> Worth adding a test if there's a super simple one to copy+paste+switch-to-ts?

We are not doing anything special with these extensions. Could be an example but I don't think we should assert that typescript config works with webpack because that's webpacks job.

**Comment by jbedard** [comment]
Did you verify it works though? I wonder if webpack needs a typescript loader setup for this to work, and we should not be encouraging that (webpack doing everything in the world in a non-cacheable way defeats the purpose of using bazel).

**Comment by jbedard** [comment]
If `node-interpret` handles it and not a webpack typescript plugin then 👍 

I just don't like the idea of rules_webpack users setting up a webpack typescript plugin, that defeats the purpose of rules_ts...

**Review by jbedard — APPROVED** [review]

**Pull request merged**
