### PR TITLE
feat: import toolchains to use for copy actions

### LINKED ISSUE #134: [Bug]: aspect_bazel_lib's "coreutils_toolchain_type" is not configured as needed
### What happened?

Per [preceding discussion in the "general" channel](https://bazelbuild.slack.com/archives/CA31HN1T3/p1701094918870129?thread_ts=1700005837.021159&cid=CA31HN1T3) of the "Bazel" Slack workspace, when trying to use the _rules_webpack_ Bazel module at [the released version 0.13.0](https://github.com/aspect-build/rules_webpack/releases/tag/v0.13.0), the `webpack_bundle` rule fails to find the _coreutils_ toolchain that it needs, per the following error:
```
ERROR: /some/path/BUILD.bazel:117:15: in _webpack_bundle rule //path/app:dist: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_seh/c8bba5caec7d941b54eb1f99ff1041dd/external/aspect_rules_webpack~0.13.0/webpack/private/webpack_bundle.bzl", line 166, column 34, in _impl
		copy_files_to_bin_actions(ctx, inputs) + no_copy_bin_inputs,
	File "/private/var/tmp/_bazel_seh/c8bba5caec7d941b54eb1f99ff1041dd/external/aspect_bazel_lib~2.0.1/lib/private/copy_to_bin.bzl", line 132, column 36, in copy_files_to_bin_actions
		return [copy_file_to_bin_action(ctx, file) for file in files]
	File "/private/var/tmp/_bazel_seh/c8bba5caec7d941b54eb1f99ff1041dd/external/aspect_bazel_lib~2.0.1/lib/private/copy_to_bin.bzl", line 84, column 21, in copy_file_to_bin_action
		copy_file_action(ctx, file, dst)
	File "/private/var/tmp/_bazel_seh/c8bba5caec7d941b54eb1f99ff1041dd/external/aspect_bazel_lib~2.0.1/lib/private/copy_file.bzl", line 84, column 31, in copy_file_action
		coreutils = ctx.toolchains[_COREUTILS_TOOLCHAIN].coreutils_info
Error: In _webpack_bundle rule //path/app:dist, toolchain type @aspect_bazel_lib~2.0.1//lib:coreutils_toolchain_type was requested but only types [] are configured
```

See these recent changes in other Bazel repositories that address this problem:
- aspect-build/rules_esbuild#165
- aspect-build/rules_js#1355
- aspect-build/rules_ts#484

### Version

Development (host) and target OS/architectures:

Output of `bazel --version`: `bazel 6.4.0- (@non-git)` (installed via Nix)

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

| Module | Version |
|---|---|
| _aspect_bazel_lib_ | 2.0.1 |
|  _aspect_rules_esbuild_ | 0.16.0 |
|  _aspect_rules_js_ | 1.34.1 |
|  _aspect_rules_ts_ | 2.1.0 |
|  _aspect_rules_webpack_ | 0.13.0 |

Language(s) and/or frameworks involved:
- JavaScript
- TypeScript

### How to reproduce

Using the Bazel modules noted above, define a target like the following in a _BUILD.bazel_ file:

```bazel
load(
    "@aspect_rules_webpack//webpack:defs.bzl",
    "webpack_bundle",
)

# ...

webpack_bundle(
    name = "dist",
    srcs = [
        ":srcs",
    ],
    node_modules = "//:node_modules",
    output_dir = True,
    webpack_config = "webpack.config.js",
)
```

### PR DESCRIPTION
**Pull request by seh**
Register the "coreutils" toolchains using definitions imported from the _bazel_lib_ Bazel repository in order to allow use of this module with _bazel_lib_ version 2 and later.

---

### Type of change

New feature or functionality (change which adds functionality)

### Test plan

Covered by existing test cases

See aspect-build/rules_esbuild#165 for precedent.

Fixes #134.

### CODE REVIEW

**Review by kormide — APPROVED** [review]
LGTM :+1:

**Review by gregmagolan — APPROVED** [review]
Looks great. Thanks for the update!

**Comment by gregmagolan** [comment]
The CI failure with Bazel 5.3.2 looks familiar:
```
ERROR: /home/runner/.cache/bazel/_bazel_runner/3583e71b01fa1c6a4fe6bf126ed74da3/external/aspect_bazel_lib/lib/private/BUILD.bazel:253:12: no such target '@local_config_platform//:constraints.bzl': target 'constraints.bzl' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["constraints.bzl"])' to /BUILD?) defined by /home/runner/.cache/bazel/_bazel_runner/3583e71b01fa1c6a4fe6bf126ed74da3/external/local_config_platform/BUILD.bazel and referenced by '@aspect_bazel_lib//lib/private:platform_utils'
```

We'll have to green this up before landing. I'll look deeper later tonight or tomorrow when I have some time.

**Comment by seh** [comment]
> The CI failure with Bazel 5.3.2 looks familiar:

Just by way of the error message, it sounds like it may be related to bazelbuild/bazel#15175, though in this case [the failure was with Ubuntu Linux](https://github.com/aspect-build/rules_webpack/actions/runs/7174687016/job/19537735162?pr=135), not macOS.

Reading further, there is aspect-build/bazel-lib#392. You noted in https://github.com/aspect-build/bazel-lib/issues/392#issuecomment-1464012521 that there's a workaround that my patch here undid, by way of removing the "override_local_config_platform" attribute value supplied to `aspect_bazel_lib_dependencies`. That was me just aping what I saw in the similar patches against [_rules_esbuild_](https://github.com/aspect-build/rules_esbuild/pull/165/files#diff-5493ff8e9397811510e780de47c57abb70137f1afe85d1519130dc3679d60ce5R23) and [_rules_ts_](https://github.com/aspect-build/rules_ts/pull/484/files#diff-5493ff8e9397811510e780de47c57abb70137f1afe85d1519130dc3679d60ce5R28). Should I try adding that attribute back in?

**Comment by seh** [comment]
> Should I try adding that attribute back in?

Commit 7848eb2e5b7a2167d6c0abddf9960a566d0c331f adds that "override_local_config_platform" attribute back into the call to `aspect_bazel_lib_dependencies` in the _WORKSPACE_ file.

**Comment by seh** [comment]
Can we please allow this most recent commit to pass through the CI workflow? I'd like to see whether it resolves the previous problem.

**Comment by seh** [comment]
> Commit [7848eb2](https://github.com/aspect-build/rules_webpack/commit/7848eb2e5b7a2167d6c0abddf9960a566d0c331f) adds that "override_local_config_platform" attribute back into the call to `aspect_bazel_lib_dependencies` in the _WORKSPACE_ file.

Well, clearly that didn't work. That attribute is no longer known to `aspect_bazel_lib_dependencies`.

**Comment by seh** [comment]
I removed that previous attempt to use the "override_local_config_platform" attribute (per https://github.com/aspect-build/rules_webpack/pull/135#issuecomment-1859238445).

Do we need to continue supporting Bazel version 5.3.2 in our CI workflow?

**Comment by gregmagolan** [comment]
I'm working on a PR to bump all the bazel deps and test only on Bazel 7 & 6. That will drop Bazel 5 from the CI matrix.

**Pull request merged**
